### ISSUE TITLE
Missing steps in microbit Wonder Building Kit - Case 05: Rotary Chairs

### ISSUE THREAD

**Issue by lboue** [elecfreaks/learn.elecfreaks.com#4]
### Issue

Missing steps in [Wonder_Building_Kit - Case 05: Rotary Chairs](https://elecfreaks.com/learn-en/microbitKit/Wonder_Building_Kit/Case_05.html#bricks-build-up) documentation.

#### Step 24
![image](https://user-images.githubusercontent.com/938089/213907218-d721ea07-ef86-40d4-b91d-28c15c76b730.png)

#### Finished model
There are steps missing to get to the full model:
![image](https://user-images.githubusercontent.com/938089/213907234-f0850519-9d8b-4cf2-b59c-3cadd234daed.png)

**Comment by lah-1201** [comment]
The building block structure steps are complete, and micro: bit needs to be downloaded before installation
